version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: flask123
      POSTGRES_DB: flaskDB
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: hello.py
      FLASK_ENV: development
      DB_USER: flask
      DB_PASSWORD: flask123
      DB_HOST: db
      DB_NAME: flaskDB

volumes:
  db_data:

